dcConsData = [

  {"name":"편안.png",		"keywords":["편안"],					"tags":["짤"]},
  {"name":"꺼라.jpg",		"keywords":["꺼라"],					"tags":["짤"]},
  {"name":"나무위키.png",		"keywords":["나무위키"],					"tags":["짤"]},
  {"name":"태양흠.gif",		"keywords":["태양"],					"tags":["움짤"]},
  {"name":"그루트1.gif",		"keywords":["그루트1"],					"tags":["움짤"]},
  {"name":"그루트2.gif",		"keywords":["그루트2"],					"tags":["움짤"]},
  {"name":"그루트.gif",		"keywords":["그루트"],					"tags":["움짤"]},
  {"name":"그루트3.gif",		"keywords":["그루트3"],					"tags":["움짤"]},
  {"name":"그루트4.gif",		"keywords":["그루트4"],					"tags":["움짤"]},
  {"name":"그루트5.gif",		"keywords":["그루트5"],					"tags":["움짤"]},

  {"name":"AMD.png",		"keywords":["암드"],					"tags":["짤"]},
  {"name":"INTEL.png",		"keywords":["인텔"],					"tags":["짤"]},
  {"name":"sega.png",		"keywords":["쎄가" , "세가"],					"tags":["짤" , "뿌테"]},
  {"name":"기타매우정상.png",		"keywords":["매우정상"],					"tags":["짤"]},
  {"name":"기타불편.png",		"keywords":["불편"],					"tags":["짤"]},
  {"name":"기타상담필요.png",		"keywords":["상담필요"],					"tags":["짤"]},
  {"name":"기타유다희1.png",		"keywords":["유다희"],					"tags":["짤"]},
  {"name":"기타형이왜.png",		"keywords":["형이왜"],					"tags":["짤"]},
  {"name":"꼭사라.png",		"keywords":["꼭사라"],					"tags":["짤"]},
  {"name":"눈물소닉.png",		"keywords":["눈물소닉"],					"tags":["짤" , "소닉"]},
  {"name":"눈물닉너클즈.png",		"keywords":["눈물소닉너클즈"],					"tags":["짤" , "소닉"]},
  {"name":"눈물닉에이미.png",		"keywords":["눈물소닉에이미"],					"tags":["짤" , "소닉"]},
  {"name":"눈물닉테일즈.png",		"keywords":["눈물소닉테일즈"],					"tags":["짤" , "소닉"]},
  {"name":"데헷.png",		"keywords":["데헷"],					"tags":["짤"]},
  {"name":"따봉.png",		"keywords":["따봉"],					"tags":["짤"]},
  {"name":"메롱.png",		"keywords":["메롱"],					"tags":["짤"]},
  {"name":"메모장.png",		"keywords":["메모장"],					"tags":["짤"]},
  {"name":"브이.png",		"keywords":["브이"],					"tags":["짤"]},
  {"name":"블러드트레일.png",		"keywords":["블러드트레일"],					"tags":["짤"]},
  {"name":"비블썸프.png",		"keywords":["비블썸프"],					"tags":["짤"]},
  {"name":"뿅뿅.png",		"keywords":["뿅"],					"tags":["짤"]},
  {"name":"삐침.png",		"keywords":["삐침"],					"tags":["짤"]},
  {"name":"산소답답.png",		"keywords":["답답"],					"tags":["짤"]},
  {"name":"수동발전.png",		"keywords":["수동발전"],					"tags":["짤"]},
  {"name":"스웩흠.png",		"keywords":["스웩흠"],					"tags":["짤"]},
  {"name":"심의공포.png",		"keywords":["공포"],					"tags":["짤"]},
  {"name":"심의범죄.png",		"keywords":["범죄"],					"tags":["짤"]},
  {"name":"심의사행.png",		"keywords":["사행"],					"tags":["짤"]},
  {"name":"심의선정.png",		"keywords":["선정"],					"tags":["짤"]},
  {"name":"심의성인.png",		"keywords":["성인"],					"tags":["짤"]},
  {"name":"심의약물.png",		"keywords":["약물"],					"tags":["짤"]},
  {"name":"심의언어.png",		"keywords":["언어"],					"tags":["짤"]},
  {"name":"심의폭력.png",		"keywords":["폭력"],					"tags":["짤"]},
  {"name":"오키.png",		"keywords":["오키"],					"tags":["짤"]},
  {"name":"와아.png",		"keywords":["와아"],					"tags":["짤"]},
  {"name":"우우.png",		"keywords":["우우"],					"tags":["짤"]},
  {"name":"위자드.png",		"keywords":["위자드"],					"tags":["짤"]},
  {"name":"위자드2.png",		"keywords":["위자드2"],					"tags":["짤"]},
  {"name":"위자드3.png",		"keywords":["위자드3"],					"tags":["짤"]},
  {"name":"일루미나티.png",		"keywords":["일루미나티"],					"tags":["짤"]},
  {"name":"제프잔짜잔.png",		"keywords":["잔짜잔1"],					"tags":["짤"]},
  {"name":"제프짜잔.png",		"keywords":["짜잔1"],					"tags":["짤"]},
  {"name":"철컹.png",		"keywords":["철컹"],					"tags":["짤"]},
  {"name":"캐피탈이지붐.jpg",		"keywords":["이지붐"],					"tags":["짤"]},
  {"name":"트럼프따봉.png",		"keywords":["트럼프따봉"],					"tags":["짤"]},
  {"name":"트리키.png",		"keywords":["트리키"],					"tags":["짤"]},
  {"name":"팝콘.png",		"keywords":["팝콘"],					"tags":["짤"]},
  {"name":"헤으윽.png",		"keywords":["헤으윽"],					"tags":["짤"]},
  {"name":"흠.png",		"keywords":["흠"],					"tags":["짤"]},
  {"name":"흠2.png",		"keywords":["흠2"],					"tags":["짤"]},
  {"name":"흠흠흠.png",		"keywords":["흠흠흠"],					"tags":["짤"]},
  {"name":"역가서순.png",		"keywords":["서순"],					"tags":["짤"]},
  {"name":"역가순서.png",		"keywords":["순서"],					"tags":["짤"]},
  {"name":"싸닉.png",		"keywords":["싸닉"],					"tags":["짤"]},
  {"name":"골든싸닉.png",		"keywords":["골든싸닉"],					"tags":["짤"]},
  {"name":"사딸라.png",		"keywords":["사딸라"],					"tags":["짤"]},
  {"name":"따일즈.png",		"keywords":["따일즈"],					"tags":["짤"]},
  {"name":"나클즈.png",		"keywords":["나클즈"],					"tags":["짤"]},
  {"name":"갓겜.png",		"keywords":["갓겜"],					"tags":["짤"]},
  {"name":"사냥.png",		"keywords":["사냥"],					"tags":["짤"]},
  {"name":"우서.png",		"keywords":["우서"],					"tags":["짤"]},
  {"name":"자그거.png",		"keywords":["자그거"],					"tags":["짤"]},
  {"name":"리정.jpg",		"keywords":["인정", "ㅇㅈ" ,"린정"],					"tags":["짤"]},

  {"name":"국뽕펄럭1.gif",		"keywords":["펄럭"],					"tags":["움짤"]},
  {"name":"ppap.gif",		"keywords":["ppap"],					"tags":["움짤"]},
  {"name":"무지개깃발.gif",		"keywords":["무지개깃발"],					"tags":["움짤"]},
  {"name":"예풍당당.gif",		"keywords":["예풍당당"],					"tags":["움짤"]},
  {"name":"이풍당당.gif",		"keywords":["이풍당당"],					"tags":["움짤"]},
  {"name":"이풍당당2.gif",		"keywords":["이풍당당2"],					"tags":["움짤"]},
  {"name":"이풍당당3.gif",		"keywords":["이풍당당3"],					"tags":["움짤"]},
  {"name":"트로피카나.gif",		"keywords":["트로피카나"],					"tags":["움짤"]},
  {"name":"트로피카나2.gif",		"keywords":["트로피카나2"],					"tags":["움짤"]},
  {"name":"기타댕댕.gif",		"keywords":["댕댕"],					"tags":["움짤"]},
  {"name":"뚱이.gif",		"keywords":["뚱이"],					"tags":["움짤"]},
  {"name":"라푼젤.gif",		"keywords":["라푼젤"],					"tags":["움짤"]},
  {"name":"문풍당당1.gif",		"keywords":["문풍당당"],					"tags":["움짤"]},
  {"name":"문풍당당2.gif",		"keywords":["문풍당당2"],					"tags":["움짤"]},
  {"name":"문풍당당3.gif",		"keywords":["문풍당당3"],					"tags":["움짤"]},
  {"name":"벤브꼬우면.gif",		"keywords":["꼬우면"],					"tags":["움짤"]},
  {"name":"벤브리틀.gif",		"keywords":["리틀"],					"tags":["움짤"]},
  {"name":"벤브버그.gif",		"keywords":["버그"],					"tags":["움짤"]},
  {"name":"벤브의도.gif",		"keywords":["의도"],					"tags":["움짤"]},
  {"name":"불편2.gif",		"keywords":["불편2"],					"tags":["움짤"]},
  {"name":"불편불.gif",		"keywords":["불편불"],					"tags":["움짤"]},
  {"name":"불편해짐.gif",		"keywords":["불편해짐"],					"tags":["움짤"]},
  {"name":"소닉왜곡.gif",		"keywords":["소닉왜곡"],					"tags":["움짤"]},
  {"name":"소닉왜곡테일즈.gif",		"keywords":["소닉왜곡테일즈"],					"tags":["움짤"]},
  {"name":"시공편안.gif",		"keywords":["시공편안"],					"tags":["움짤"]},
  {"name":"심영박수.gif",		"keywords":["심영박수"],					"tags":["움짤"]},
  {"name":"어쩔.gif",		"keywords":["어쩔"],					"tags":["움짤"]},
  {"name":"역가골든무말모.gif",		"keywords":["골든무말모"],					"tags":["움짤"]},
  {"name":"예풍당당.gif",		"keywords":["예풍당당"],					"tags":["움짤"]},
  {"name":"우리핵드럼.gif",		"keywords":["우리핵드럼"],					"tags":["움짤"]},
  {"name":"우리핵박수1.gif",		"keywords":["우리핵박수"],					"tags":["움짤"]},
  {"name":"우리핵박수2.gif",		"keywords":["우리핵박수2"],					"tags":["움짤"]},
  {"name":"우리핵박수3.gif",		"keywords":["우리핵박수3"],					"tags":["움짤"]},
  {"name":"우리핵병신.gif",		"keywords":["우리핵병신"],					"tags":["움짤"]},
  {"name":"우리핵빵야.gif",		"keywords":["우리핵빵야"],					"tags":["움짤"]},
  {"name":"우리핵시벌.gif",		"keywords":["우리핵시벌"],					"tags":["움짤"]},
  {"name":"우리핵쌍안경.gif",		"keywords":["우리핵쌍안경"],					"tags":["움짤"]},
  {"name":"우리핵아닌데.gif",		"keywords":["우리핵아닌데"],					"tags":["움짤"]},
  {"name":"우리핵안녕.gif",		"keywords":["우리핵안녕"],					"tags":["움짤"]},
  {"name":"우리핵안녕2.gif",		"keywords":["우리핵안녕2"],					"tags":["움짤"]},
  {"name":"우리핵안무.gif",		"keywords":["우리핵안무"],					"tags":["움짤"]},
  {"name":"우리핵투정.gif",		"keywords":["우리핵투정"],					"tags":["움짤"]},
  {"name":"고맙네.gif",		"keywords":["고맙네"],					"tags":["움짤", "돌겜"]},
  {"name":"노루야캐요.gif",		"keywords":["야캐요", "노루야캐요" , "약해요"],		"tags":["움짤", "돌겜"]},
  {"name":"노잼.gif",		"keywords":["노잼" , "핵노잼"],	 	"tags":["움짤"]},
  {"name":"받아치기.gif",		"keywords":["받아치기", "안녕하살법받아치기"],			"tags":["움짤"]},
  {"name":"불만.gif",		"keywords":["불만", "핵불만"],					"tags":["움짤"]},
  {"name":"빛당테.gif",		"keywords":["빛당테"],					"tags":["움짤", "돌겜"]},
  {"name":"제당조.gif",		"keywords":["제당조"],					"tags":["움짤", "돌겜"]},
  {"name":"히히크크.gif",		"keywords":["히히카드", "크크카드"],					"tags":["움짤", "돌겜"]},
  {"name":"안녕.gif",		"keywords":["안녕" , "핵안녕"],					"tags":["움짤"]},
  {"name":"안녕하살법.gif",		"keywords":["안녕하살법"],					"tags":["움짤"]},

  {"name":"자기과시.gif",		"keywords":["자기과시"],					"tags":["움짤"]},
  {"name":"정신.gif",		"keywords":["정신"],					"tags":["움짤"]},
  {"name":"제리깔깔.gif",		"keywords":["제깔깔"],					"tags":["움짤"]},
  {"name":"제리낑기잇.gif",		"keywords":["낑기잇"],					"tags":["움짤"]},
  {"name":"제리죽음.gif",		"keywords":["죽음"],					"tags":["움짤"]},
  {"name":"제리지휘.gif",		"keywords":["지휘" , "훈수"],					"tags":["움짤"]},
  {"name":"제리튀튀.gif",		"keywords":["튀튀"],					"tags":["움짤"]},
  {"name":"제프잔짜잔.gif",		"keywords":["잔짜잔"],					"tags":["움짤"]},
  {"name":"제프짜잔.gif",		"keywords":["짜잔"],					"tags":["움짤"]},
  {"name":"좋은말네말맞.gif",		"keywords":["네말맞"],					"tags":["움짤"]},
  {"name":"좋은말멋있다.gif",		"keywords":["멋있다"],					"tags":["움짤"]},
  {"name":"좋은말좋겠다.gif",		"keywords":["좋겠다"],					"tags":["움짤"]},
  {"name":"좋은말짱이야.gif",		"keywords":["짱이야"],					"tags":["움짤"]},
  {"name":"좋은말축하해.gif",		"keywords":["축하해"],					"tags":["움짤"]},
  {"name":"직관.gif",		"keywords":["직관"],					"tags":["움짤"]},
  {"name":"징징이.gif",		"keywords":["징징이"],					"tags":["움짤"]},
  {"name":"찐따.gif",		"keywords":["찐따"],					"tags":["움짤"]},
  {"name":"카광단두개.gif",		"keywords":["단두개"],					"tags":["움짤"]},
  {"name":"카광단세개.gif",		"keywords":["단세개"],					"tags":["움짤"]},
  {"name":"카광단하나.gif",		"keywords":["단하나"],					"tags":["움짤"]},
  {"name":"카광뭐어라고.gif",		"keywords":["뭐라고"],					"tags":["움짤"]},
  {"name":"카광저오빠.gif",		"keywords":["저오빠"],					"tags":["움짤"]},
  {"name":"카광혼자오셨.gif",		"keywords":["혼자오셨"],					"tags":["움짤"]},
  {"name":"트럼프끄덕.gif",		"keywords":["트럼프끄덕"],					"tags":["움짤"]},
  {"name":"트럼프리듬.gif",		"keywords":["트럼프리듬"],					"tags":["움짤"]},
  {"name":"파킨2.gif",		"keywords":["파킨"],					"tags":["움짤"]},
  {"name":"편안해짐.gif",		"keywords":["편안해짐"],					"tags":["움짤"]},
  {"name":"혼란앵무.gif",		"keywords":["혼란앵무"],					"tags":["움짤"]},
  {"name":"혼란흠.gif",		"keywords":["혼란흠"],					"tags":["움짤"]},
  {"name":"회전흠.gif",		"keywords":["회전흠"],					"tags":["움짤"]},
  {"name":"회전흠2.gif",		"keywords":["회전흠2"],					"tags":["움짤"]},
  {"name":"회전흠3.gif",		"keywords":["회전흠3"],					"tags":["움짤"]},
  {"name":"어케이겼노.gif",		"keywords":["어케이겼노"],					"tags":["움짤"]},
  {"name":"어케했노.gif",		"keywords":["어케했노"],					"tags":["움짤"]},
  {"name":"두근두근.gif",		"keywords":["두근두근"],					"tags":["움짤"]},

  {"name":"가젤1.gif",		"keywords":["가젤1"],					"tags":["쥬톱" , "움짤"]},
  {"name":"가젤2.gif",		"keywords":["가젤2"],					"tags":["쥬톱" , "움짤"]},
  {"name":"가젤3.gif",		"keywords":["가젤3"],					"tags":["쥬톱" , "움짤"]},
  {"name":"가젤4.gif",		"keywords":["가젤4"],					"tags":["쥬톱" , "움짤"]},
  {"name":"가젤.gif",		"keywords":["가젤"],					"tags":["쥬톱" , "움짤"]},
  {"name":"닉놀람.gif",		"keywords":["닉놀람"],					"tags":["쥬톱" , "움짤"]},
  {"name":"닉댄스.gif",		"keywords":["닉댄스"],					"tags":["쥬톱" , "움짤"]},
  {"name":"닉띠용.gif",		"keywords":["닉띠용"],					"tags":["쥬톱" , "움짤"]},
  {"name":"닉주디.gif",		"keywords":["닉주디"],					"tags":["쥬톱" , "움짤"]},
  {"name":"닉주디2.gif",		"keywords":["닉주디2"],					"tags":["쥬톱" , "움짤"]},
  {"name":"닉찡긋.gif",		"keywords":["닉찡긋"],					"tags":["쥬톱" , "움짤"]},
  {"name":"닉헤가오.gif",		"keywords":["닉헤가오"],					"tags":["쥬톱" , "움짤"]},
  {"name":"보고.gif",		"keywords":["보고"],					"tags":["쥬톱" , "움짤쥬톱" , "움짤"]},
  {"name":"보고2.gif",		"keywords":["보고2"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주디노우.gif",		"keywords":["주디노우", "노우"],					"tags":["쥬톱" , "움짤쥬톱" , "움짤"]},
  {"name":"주디놀람.gif",		"keywords":["주디놀람"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주디떡락.gif",		"keywords":["주디떡락" , "떡락"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주디떡상.gif",		"keywords":["주디떡상" , "떡상"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주디띠용.gif",		"keywords":["주디띠용" , "띠용"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주디폴짝.gif",		"keywords":["주디폴짝" , "폴짝"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주톱호랑이1.gif",		"keywords":["호랑이1"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주톱호랑이2.gif",		"keywords":["호랑이2"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주톱호랑이3.gif",		"keywords":["호랑이3"],					"tags":["쥬톱" , "움짤"]},
  {"name":"주톱호랑이4.gif",		"keywords":["호랑이"],					"tags":["쥬톱" , "움짤"]},

  {"name":"눈물.png",		"keywords":["눈물"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물드라코.png",		"keywords":["눈물드라코"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물라피나.png",		"keywords":["눈물라피나"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물렘레스.png",		"keywords":["눈물렘레스"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물루루.png",		"keywords":["눈물루루"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물리스쿠마.png",		"keywords":["눈물리스쿠마"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물링고.png",		"keywords":["눈물링고"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물마구로.png",		"keywords":["눈물마구로"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물사탄.png",		"keywords":["눈물사탄"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물세죠.png",		"keywords":["눈물세죠"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물스케토우가라.png",		"keywords":["눈물스케토우가라"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물시그.png",		"keywords":["눈물시그"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물아르르.png",		"keywords":["눈물아르르"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물아미티.png",		"keywords":["눈물아미티"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물에스.png",		"keywords":["눈물에스"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물에코로.png",		"keywords":["눈물에코로"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물엑스.png",		"keywords":["눈물엑스"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물오.png",		"keywords":["눈물오"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물윗치.png",		"keywords":["눈물윗치"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물제이엘.png",		"keywords":["눈물제이엘"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물제트.png",		"keywords":["눈물제트"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물크루크.png",		"keywords":["눈물크루크"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물티.png",		"keywords":["눈물티"],					"tags":["뿌테" , "짤"]},
  {"name":"눈물페리.png",		"keywords":["눈물페리"],					"tags":["뿌테" , "짤"]},
  {"name":"드라코.png",		"keywords":["드라코"],					"tags":["뿌테" ,"짤"]},
  {"name":"리스쿠마.png",		"keywords":["리스쿠마"],					"tags":["뿌테" ,"짤"]},
  {"name":"링고.png",		"keywords":["링고"],					"tags":["뿌테" ,"짤"]},
  {"name":"뿌요빠요엔1.png",		"keywords":["빠요엔"],					"tags":["뿌테"]},
  {"name":"뿌요빠요엔2.gif",		"keywords":["빠요엔2"],					"tags":["뿌테"]},
  {"name":"뿌요빠요엔3.gif",		"keywords":["빠요엔3"],					"tags":["뿌테"]},
  {"name":"시그.png",		"keywords":["시그"],					"tags":["뿌테"]},
  {"name":"시그뻐큐.png",		"keywords":["시그뻐큐"],					"tags":["뿌테"]},
  {"name":"아르르.png",		"keywords":["아르르"],					"tags":["뿌테"]},
  {"name":"아르르뻐큐.png",		"keywords":["아르르뻐큐"],					"tags":["뿌테"]},
  {"name":"아미티.png",		"keywords":["아미티"],					"tags":["뿌테"]},
  {"name":"에스뻐큐.png",		"keywords":["에스뻐큐"],					"tags":["뿌테"]},
  {"name":"에이아이.png",		"keywords":["에이아이"],					"tags":["뿌테"]},
  {"name":"에코로.png",		"keywords":["에코로"],					"tags":["뿌테"]},
  {"name":"오.png",		"keywords":["오"],					"tags":["뿌테"]},
  {"name":"윗치.png",		"keywords":["윗치"],					"tags":["뿌테"]},
  {"name":"제이엘.png",		"keywords":["제이엘"],					"tags":["뿌테"]},
  {"name":"제이엘뻐큐.png",		"keywords":["제이엘뻐큐"],					"tags":["뿌테"]},
  {"name":"카벙클.png",		"keywords":["카방클", "카방"],					"tags":["뿌테"]},
  {"name":"페리뻐큐.png",		"keywords":["페리뻐큐"],					"tags":["뿌테"]},

  {"name":"난죽택.gif",		"keywords":["난죽택"],					"tags":["돌겜"]},
  {"name":"정규거지.gif",		"keywords":["뭐?" , "정규거지"],					"tags":["돌겜"]},
  {"name":"하스삭제.gif",		"keywords":["하스삭제", "돌겜삭제"],					"tags":["돌겜"]},
  {"name":"화난닭.gif",		"keywords":["화난닭"],					"tags":["돌겜"]},
  {"name":"니놈추.png",		"keywords":["니놈추", "네놈추"],					"tags":["돌겜"]},
  {"name":"우정대.png",		"keywords":["우정대","우정데"],					"tags":["돌겜"]},

  {"name":"미니울랄라.gif",		"keywords":["울랄라"],					"tags":["미니"]},
  {"name":"미니간절.gif",		"keywords":["간절"],					"tags":["미니"]},
  {"name":"미니감동.gif",		"keywords":["감동"],					"tags":["미니"]},
  {"name":"미니감사.gif",		"keywords":["감사"],					"tags":["미니"]},
  {"name":"미니감탄.gif",		"keywords":["감탄"],					"tags":["미니"]},
  {"name":"미니꺼져.gif",		"keywords":["꺼졍"],					"tags":["미니"]},
  {"name":"미니꺼져2.gif",		"keywords":["꺼져2"],					"tags":["미니"]},
  {"name":"미니나나.gif",		"keywords":["나나"],					"tags":["미니"]},
  {"name":"미니난준택.gif",		"keywords":["난준택"],					"tags":["미니"]},
  {"name":"미니놀람.gif",		"keywords":["놀람"],					"tags":["미니"]},
  {"name":"미니눈물.gif",		"keywords":["후엥"],					"tags":["미니"]},
  {"name":"미니뒷태.gif",		"keywords":["뒷태"],					"tags":["미니"]},
  {"name":"미니득실.gif",		"keywords":["빤스들"],					"tags":["미니"]},
  {"name":"미니등장.gif",		"keywords":["등장"],					"tags":["미니"]},
  {"name":"미니따봉.gif",		"keywords":["미니따봉"],					"tags":["미니"]},
  {"name":"미니리듬.gif",		"keywords":["리듬"],					"tags":["미니"]},
  {"name":"미니박수.gif",		"keywords":["박수"],					"tags":["미니"]},
  {"name":"미니빤스런.gif",		"keywords":["빤스런"],					"tags":["미니"]},
  {"name":"미니뿌뿌.gif",		"keywords":["뿌뿌"],					"tags":["미니"]},
  {"name":"미니센세하이.gif",		"keywords":["센세하이" , "센하"],					"tags":["미니"]},
  {"name":"미니신남.gif",		"keywords":["신남"],					"tags":["미니"]},
  {"name":"미니안뇽.gif",		"keywords":["안뇽"],					"tags":["미니"]},
  {"name":"미니잘가.gif",		"keywords":["잘가"],					"tags":["미니"]},
  {"name":"미니좋은하루.gif",		"keywords":["좋은하루"],					"tags":["미니"]},
  {"name":"미니캬.gif",		"keywords":["캬"],					"tags":["미니"]},
  {"name":"미니펑.gif",		"keywords":["펑"],					"tags":["미니"]},
  {"name":"미니핥짝.gif",		"keywords":["핥짝"],					"tags":["미니"]},
  {"name":"미니핥짝2.gif",		"keywords":["핥짝2"],					"tags":["미니"]},
  {"name":"미니환호.gif",		"keywords":["환호"],					"tags":["미니"]},
  {"name":"미니흠칫.gif",		"keywords":["흠칫"],					"tags":["미니"]},
  {"name":"미니흠칫2.gif",		"keywords":["흠칫2"],					"tags":["미니"]},
  {"name":"미니흥얼.gif",		"keywords":["흥얼"],					"tags":["미니"]},
  {"name":"생축.gif",		"keywords":["생축"],					"tags":["미니"]},

  {"name":"손님빨갱이.gif",		"keywords":["빨갱이", "화남"],					"tags":["롤코타", "손님", "움짤"]},
	{"name":"손님멀미1.gif",		"keywords":["멀미", "멀미1"], 					"tags":["롤코타", "손님"]},
	{"name":"손님멀미2.gif",		"keywords":["멀미2"],						"tags":["롤코타", "손님", "움짤"]},
	{"name":"손님멀미3.gif", 		"keywords":["멀미3"],						"tags":["롤코타", "손님", "움짤"]},
	{"name":"손님피곤.gif", 		"keywords":["피곤"],						"tags":["롤코타", "손님"]},
	{"name":"손님행복1.gif", 		"keywords":["행복", "행복1"],					"tags":["롤코타", "손님"]},
	{"name":"손님행복2.gif", 		"keywords":["행복2"],						"tags":["롤코타", "손님"]},
	{"name":"손님무표정.gif", 		"keywords":["무표정"], 						"tags":["롤코타", "손님"]},
	{"name":"손님불행1.gif", 		"keywords":["불행", "불행1"],					"tags":["롤코타", "손님"]},
	{"name":"손님불행2.gif", 		"keywords":["불행2"], 						"tags":["롤코타", "손님"]},

  {"name":"기구보트.png",		"keywords":["보트"],					"tags":["롤코타" , "기구"]},
  {"name":"기구비행접시.png",		"keywords":["비행접시"],					"tags":["롤코타" , "기구"]},
  {"name":"기구삐뚤어진집.png",		"keywords":["삐뚤어진집"],					"tags":["롤코타" , "기구"]},
  {"name":"기구서스펜디드모노레일.png",		"keywords":["서스펜디드모노레일"],					"tags":["롤코타" , "기구"]},
  {"name":"기구서커스.png",		"keywords":["서커스"],					"tags":["롤코타" , "기구"]},
  {"name":"기구스페어링.png",		"keywords":["스페어링"],					"tags":["롤코타" , "기구"]},
  {"name":"기구스플래시보트.png",		"keywords":["스플래시보"],					"tags":["롤코타" , "기구"]},
  {"name":"기구양탄자.png",		"keywords":["양탄자"],					"tags":["롤코타" , "기구"]},
  {"name":"기구엔터프라이즈.png",		"keywords":["엔터프라이즈"],					"tags":["롤코타" , "기구"]},
  {"name":"기구엘리베이터.png",		"keywords":["엘리베이터" , "엘베"],					"tags":["롤코타" , "기구"]},
  {"name":"기구영화관.png",		"keywords":["영화관"],					"tags":["롤코타" , "기구"]},
  {"name":"기구워터슬라이드.png",		"keywords":["워터슬라이드" , "슬라이드", "보트슬라이드"],					"tags":["롤코타" , "기구"]},
  {"name":"기구유령기차.png",		"keywords":["유령기차"],					"tags":["롤코타" , "기구"]},
  {"name":"기구자이로드롭.png",		"keywords":["자이로드롭"],					"tags":["롤코타" , "기구"]},
  {"name":"기구자전거.png",		"keywords":["자전거"],					"tags":["롤코타" , "기구"]},
  {"name":"기구전망탑.png",		"keywords":["전망탑"],					"tags":["롤코타" , "기구"]},
  {"name":"기구체어리프트.png",		"keywords":["체어리프트"],					"tags":["롤코타" , "기구"]},
  {"name":"기구카누.png",		"keywords":["카누"],					"tags":["롤코타" , "기구"]},
  {"name":"기구카라이드.png",		"keywords":["카라이드"],					"tags":["롤코타" , "기구"]},
  {"name":"기구탑스핀.png",		"keywords":["탑스핀"],					"tags":["롤코타" , "기구"]},
  {"name":"기구트램.png",		"keywords":["트램"],					"tags":["롤코타" , "기구"]},
  {"name":"기구트위스트.png",		"keywords":["트위스트"],					"tags":["롤코타" , "기구"]},
  {"name":"기구회전목마.png",		"keywords":["회전목마"],					"tags":["롤코타" , "기구"]},
  {"name":"기구후룸라이드.png",		"keywords":["후룸라이드"],					"tags":["롤코타" , "기구"]},
  {"name":"기구범퍼카.png",		"keywords":["범퍼카"],					"tags":["롤코타" , "기구"]},
  {"name":"기구백조보트.png",		"keywords":["백조보트"],					"tags":["롤코타" , "기구"]},
  {"name":"기구바이킹.png",		"keywords":["바이킹"],					"tags":["롤코타" , "기구"]},
  {"name":"기구미니헬리콥터.png",		"keywords":["헬리콥터"],					"tags":["롤코타" , "기구"]},
  {"name":"기구모형기차.png",		"keywords":["모형기차"],					"tags":["롤코타" , "기구"]},
  {"name":"기구모션시뮬레이터.png",		"keywords":["모션시뮬레이터" ,"모션시뮬"],					"tags":["롤코타" , "기구"]},
  {"name":"기구모노레일.png",		"keywords":["모노레일"],					"tags":["롤코타" , "기구"]},
  {"name":"기구메이즈.png",		"keywords":["메이즈"],					"tags":["롤코타" , "기구"]},
  {"name":"기구리버래피드.png",		"keywords":["리버래피드"],					"tags":["롤코타" , "기구"]},
  {"name":"기구런치드프리폴.png",		"keywords":["런치드프리폴" , "런치드"],					"tags":["롤코타" , "기구"]},
  {"name":"기구떼껄룩카라이드.png",		"keywords":["떼껄룩라이드" , "껄룩라이드"],					"tags":["롤코타" , "기구"]},
  {"name":"기구나선미끄럼틀.png",		"keywords":["나선미끄럼틀" , "미끄럼틀"],					"tags":["롤코타" , "기구"]},
  {"name":"기구귀신의집.png",		"keywords":["귀신의집" , "유령의집"],					"tags":["롤코타" , "기구"]},
  {"name":"기구2층전망탑.png",		"keywords":["2층전망탑"],					"tags":["롤코타" , "기구"]},
  {"name":"기구2층회전목마.png",		"keywords":["2층회전목마"],					"tags":["롤코타" , "기구"]},
  {"name":"기구360도바이킹.png",		"keywords":["360도바이킹" , "360도"],					"tags":["롤코타" , "기구"]},
  {"name":"기구고카트.png",		"keywords":["고카트"],					"tags":["롤코타" , "기구"]},
  {"name":"기구골프.png",		"keywords":["골프" , "미니골프"],					"tags":["롤코타" , "기구"]},
  {"name":"기구관람차.png",		"keywords":["관람차"],					"tags":["롤코타" , "기구"]},
  {"name":"기구리버래프트.png",		"keywords":["리버래프트"],					"tags":["롤코타" , "기구"]},
  {"name":"롤코기가.png",		"keywords":["기가"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코나선.png",		"keywords":["나선"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코레이다운.png",		"keywords":["레이다운"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코루핑.png",		"keywords":["루핑"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코리버서.png",		"keywords":["리버서"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코리버스프리폴.png",		"keywords":["리버스프리폴"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코림발진.png",		"keywords":["림발진"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코마인.png",		"keywords":["마인"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코멀티디멘션.png",		"keywords":["멀티디멘션"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코미니.png",		"keywords":["미니"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코미니서스펜디드.png",		"keywords":["미니서스펜디드" , "서스펜디드"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코버지니아.png",		"keywords":["버지니아"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코봅슬레이.png",		"keywords":["봅슬레이"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코사이드프릭션.png",		"keywords":["사이드프릭션"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코스펜디드.png",		"keywords":["스펜디드"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코수직낙하.png",		"keywords":["수직낙하"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코스탠드업.png",		"keywords":["스탠드업"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코스티플체이스.png",		"keywords":["스티플체이스"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코스파이럴.png",		"keywords":["스파이럴"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코에어파워드버티컬.png",		"keywords":["에어파워드버티컬"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코와일드마우스.png",		"keywords":["와일드마우스"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코우든.png",		"keywords":["우든"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코우든와일드광산.png",		"keywords":["우든와일드광산"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코우든와일드마우스.png",		"keywords":["우든와일드마우스"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코우든트위스터.png",		"keywords":["우든트위스터"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코워터코스터.png",		"keywords":["워터코스터"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코인버티드.png",		"keywords":["인버티드"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코주니어.png",		"keywords":["주니어"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코컴팩트인버티드.png",		"keywords":["컴팩트인버티드"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코탄광.png",		"keywords":["탄광"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코트위스터.png",		"keywords":["트위스터"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코플라잉턴.png",		"keywords":["플라잉턴"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코플로어리스.png",		"keywords":["플로어리스"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코하트라인.gif",		"keywords":["하트라인"],					"tags":["롤코타", "롤러코스터"]},
  {"name":"롤코봅슬레이.png",		"keywords":["봅슬레이"],					"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코수직낙하.png",		"keywords":["수직낙하"],					"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코우든.png",			"keywords":["우든"],						"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코탄광.png",			"keywords":["탄광"],						"tags":["롤코타", "롤러코스터"]},

	{"name":"상점ATM.png",			"keywords":["ATM"],						"tags":["롤코타", "상점"]},
	{"name":"상점병원.png",			"keywords":["병원"],						"tags":["롤코타", "상점"]},
	{"name":"상점안내소.png",		"keywords":["안내소"],						"tags":["롤코타", "상점"]},
	{"name":"상점촉수.png",			"keywords":["촉수가게"],					"tags":["롤코타", "상점"]},
	{"name":"상점풍선.png",			"keywords":["풍선가게"], 					"tags":["롤코타", "상점"]},
	{"name":"상점화장실.png",		"keywords":["화장실"],						"tags":["롤코타", "상점"]},
  {"name":"상점감자칩.png",		"keywords":["감자칩"],					"tags":["롤코타", "상점"]},
  {"name":"상점감자튀김.png",		"keywords":["감자튀김"],					"tags":["롤코타", "상점"]},
  {"name":"상점고기국수.png",		"keywords":["고기국수"],					"tags":["롤코타", "상점"]},
  {"name":"상점고기완자탕.png",		"keywords":["고기완자탕"],					"tags":["롤코타", "상점"]},
  {"name":"상점기념품.png",		"keywords":["기념품"],					"tags":["롤코타", "상점"]},
  {"name":"상점도넛.png",		"keywords":["도넛"],					"tags":["롤코타", "상점"]},
  {"name":"상점두유.png",		"keywords":["두유"],					"tags":["롤코타", "상점"]},
  {"name":"상점레모네이드.png",		"keywords":["레모네이드"],					"tags":["롤코타", "상점"]},
  {"name":"상점만두국.png",		"keywords":["만두국"],					"tags":["롤코타", "상점"]},
  {"name":"상점모자.png",		"keywords":["모자"],					"tags":["롤코타", "상점"]},
  {"name":"상점사과사탕.png",		"keywords":["사과사탕"],					"tags":["롤코타", "상점"]},
  {"name":"상점샌드위치.png",		"keywords":["샌드위치"],					"tags":["롤코타", "상점"]},
  {"name":"상점선글라스.png",		"keywords":["선글라스"],					"tags":["롤코타", "상점"]},
  {"name":"상점소세지.png",		"keywords":["소세지"],					"tags":["롤코타", "상점"]},
  {"name":"상점솜사탕.png",		"keywords":["솜사탕"],					"tags":["롤코타", "상점"]},
  {"name":"상점수정과.png",		"keywords":["수정과"],					"tags":["롤코타", "상점"]},
  {"name":"상점스타푸르트.png",		"keywords":["스타푸르트"],					"tags":["롤코타", "상점"]},
  {"name":"상점아이스크림콘.png",		"keywords":["아이스크림콘"],					"tags":["롤코타", "상점"]},
  {"name":"상점아이스티.png",		"keywords":["아이스티"],					"tags":["롤코타", "상점"]},
  {"name":"상점음료수.png",		"keywords":["음료수"],					"tags":["롤코타", "상점"]},
  {"name":"상점치킨.png",		"keywords":["치킨"],					"tags":["롤코타", "상점"]},
  {"name":"상점치킨너겟.png",		"keywords":["치킨너겟"],					"tags":["롤코타", "상점"]},
  {"name":"상점커피.png",		"keywords":["커피"],					"tags":["롤코타", "상점"]},
  {"name":"상점케이크.png",		"keywords":["케이크"],					"tags":["롤코타", "상점"]},
  {"name":"상점쿠키.png",		"keywords":["쿠키"],					"tags":["롤코타", "상점"]},
  {"name":"상점튀김쌀국수.png",		"keywords":["튀김쌀국수"],					"tags":["롤코타", "상점"]},
  {"name":"상점티셔츠.png",		"keywords":["티셔츠"],					"tags":["롤코타", "상점"]},
  {"name":"상점팝콘.png",		"keywords":["팝콘"],					"tags":["롤코타", "상점"]},
  {"name":"상점피자.png",		"keywords":["피자"],					"tags":["롤코타", "상점"]},
  {"name":"상점프레첼.png",		"keywords":["프레첼"],					"tags":["롤코타", "상점"]},
  {"name":"상점핫도그.png",		"keywords":["핫도그"],					"tags":["롤코타", "상점"]},
  {"name":"상점핫초코.png",		"keywords":["핫초코"],					"tags":["롤코타", "상점"]},
  {"name":"상점햄버거.png",		"keywords":["햄버거"],					"tags":["롤코타", "상점"]}
  ];
